// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxmcstaftbxtcdtfyljv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4bWNzdGFmdGJ4dGNkdGZ5bGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzYyMzIsImV4cCI6MjA1ODIxMjIzMn0.jXuLBJ0owFwLn-d78ayluOJhy1mv1RBF2NGNPNvmdug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);